import React,{useCallback,useEffect,useState}from'react';
import{Alert,Box,Button,Checkbox,FormControlLabel,Grid,List,ListItem,ListItemText,MenuItem,Paper,Stack,Switch,TextField,Typography}from'@mui/material';
import api from'../services/api';
export default function ReactivationPage(){const[campaigns,setCampaigns]=useState([]),[conversations,setConversations]=useState([]),[promotions,setPromotions]=useState([]),[selected,setSelected]=useState(new Set()),[notice,setNotice]=useState('');
 const[form,setForm]=useState({name:'',message_context:'',scheduled_at:'',promotion_id:'',automatic_enabled:false,inactivity_days:30,service_code:'',lead_strength:'',max_recipients:100});
 const load=useCallback(async()=>{try{const[c,v,p]=await Promise.all([api.get('/api/reactivation'),api.get('/api/conversations',{params:{source:'meta_ad',limit:100}}),api.get('/api/knowledge/promotions')]);setCampaigns(c.data);setConversations(v.data);setPromotions(p.data.filter(x=>x.active));}catch(e){setNotice(e.response?.data?.message||'No se pudo cargar.');}},[]);useEffect(()=>{load();},[load]);
 const toggle=id=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n;});
 const create=async e=>{e.preventDefault();try{await api.post('/api/reactivation',{name:form.name,message_context:form.message_context,scheduled_at:new Date(form.scheduled_at).toISOString(),promotion_id:form.promotion_id||null,automatic_enabled:form.automatic_enabled,criteria:{inactivity_days:Number(form.inactivity_days)||30,service_code:form.service_code||null,lead_strength:form.lead_strength||null,max_recipients:Number(form.max_recipients)||100},conversation_ids:[...selected]});setSelected(new Set());setForm({name:'',message_context:'',scheduled_at:'',promotion_id:'',automatic_enabled:false,inactivity_days:30,service_code:'',lead_strength:'',max_recipients:100});await load();}catch(err){setNotice(err.response?.data?.message||'No se pudo crear.');}};
 return<Stack spacing={3}><Box><Typography variant="h4">Reactivación</Typography><Typography color="text.secondary">Solo prospectos provenientes de anuncios; la automatización permanece desactivada por campaña salvo configuración explícita.</Typography></Box>{notice?<Alert severity="error" onClose={()=>setNotice('')}>{notice}</Alert>:null}
 <Paper sx={{p:3}} component="form" onSubmit={create}><Grid container spacing={2}><Grid item xs={12} md={6}><TextField required fullWidth label="Nombre de campaña" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></Grid><Grid item xs={12} md={6}><TextField required fullWidth type="datetime-local" label="Programar" InputLabelProps={{shrink:true}} value={form.scheduled_at} onChange={e=>setForm(f=>({...f,scheduled_at:e.target.value}))}/></Grid>
 <Grid item xs={12}><TextField required fullWidth multiline minRows={3} label="Mensaje/contexto aprobado" value={form.message_context} onChange={e=>setForm(f=>({...f,message_context:e.target.value}))}/></Grid><Grid item xs={12} md={6}><TextField select fullWidth label="Promoción opcional" value={form.promotion_id} onChange={e=>setForm(f=>({...f,promotion_id:e.target.value}))}><MenuItem value="">Sin promoción</MenuItem>{promotions.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</TextField></Grid>
 <Grid item xs={12} md={6}><FormControlLabel control={<Switch checked={form.automatic_enabled} onChange={e=>setForm(f=>({...f,automatic_enabled:e.target.checked}))}/>} label="Segmentación automática"/></Grid>{form.automatic_enabled?<><Grid item xs={6} md={3}><TextField fullWidth size="small" type="number" label="Días sin actividad" value={form.inactivity_days} onChange={e=>setForm(f=>({...f,inactivity_days:e.target.value}))}/></Grid><Grid item xs={6} md={3}><TextField fullWidth size="small" label="Código de servicio" value={form.service_code} onChange={e=>setForm(f=>({...f,service_code:e.target.value}))}/></Grid><Grid item xs={6} md={3}><TextField select fullWidth size="small" label="Perfil" value={form.lead_strength} onChange={e=>setForm(f=>({...f,lead_strength:e.target.value}))}><MenuItem value="">Todos</MenuItem><MenuItem value="fuerte">Fuerte</MenuItem><MenuItem value="medio">Medio</MenuItem><MenuItem value="debil">Débil</MenuItem><MenuItem value="especial">Especial</MenuItem></TextField></Grid><Grid item xs={6} md={3}><TextField fullWidth size="small" type="number" label="Máximo (1–500)" value={form.max_recipients} onChange={e=>setForm(f=>({...f,max_recipients:e.target.value}))}/></Grid></>:null}
 {!form.automatic_enabled?<Grid item xs={12}><Typography fontWeight={700}>Selecciona conversaciones</Typography><List dense sx={{maxHeight:240,overflow:'auto'}}>{conversations.map(c=><ListItem key={c.id} secondaryAction={<Checkbox checked={selected.has(c.id)} onChange={()=>toggle(c.id)}/>}><ListItemText primary={c.display_name||c.phone_normalized} secondary={`${c.last_message_preview||''} · ${c.attention_mode}`}/></ListItem>)}</List></Grid>:null}<Grid item xs={12}><Button type="submit" variant="contained" disabled={!form.scheduled_at||(!form.automatic_enabled&&selected.size===0)}>Programar campaña</Button></Grid></Grid></Paper>
 <Paper sx={{p:3}}><Typography variant="h6">Campañas</Typography><Stack spacing={1} sx={{mt:2}}>{campaigns.map(c=><Box key={c.id}><Typography fontWeight={700}>{c.name} · {c.status}</Typography><Typography variant="body2">{new Date(c.scheduled_at).toLocaleString()} · {c.sent}/{c.recipients} enviados</Typography></Box>)}</Stack></Paper></Stack>}
